language: generic
sudo: false
dist: xenial
jdk: openjdk8

env:
  global:
    BYOND_MAJOR="513"
    BYOND_MINOR="1536"

# ALL MAPS MUST BE PRESENT HERE
# IF THEY ARE NOT, YOUR BUILD WILL FAIL
matrix:
    include:
    - name: "Code"
      env: TEST=CODE
    - name: "Web"
      env: TEST=WEB
    - name: "Map - Example"
      env: TEST=MAP MAP_PATH=example
    - name: "Map - Nerva"
      env: TEST=MAP MAP_PATH=nerva
 #   - name: "Map - Glloydstation"
 #     env: TEST=MAP MAP_PATH=glloydstation
    - name: "Map - Bearcat"
      env: TEST=MAP MAP_PATH=bearcat
    - name: "Map - Away Sites"
      env: TEST=MAP MAP_PATH=away_sites_testing

cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - python
      - python-pip

script:
  - test/run-test.sh
