name: Generate Documentation

permissions:
  contents: read

on:
  push:
    branches:
    - dev
  workflow_dispatch: # allows this workflow to be manually triggered

env:
  SPACEMAN_DMM_VERSION: suite-1.7.2

jobs:
  PreFlight:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: paths-filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: .github/workflow-config/preflight-filters.yml
    outputs:
      dm: ${{ steps.filter.outputs.dm }}
  generate_documentation:
    permissions:
      contents: write # required to push the doc commit
    runs-on: ubuntu-latest
    needs: PreFlight
    if: |
      (needs.PreFlight.outputs.dm == 'true') &&
      !contains(github.event.head_commit.message, '[ci skip]')
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Cache
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
        with:
          path: ~/spaceman_dmm/${{ env.SPACEMAN_DMM_VERSION }}
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install dmdoc
        run:  scripts/install-spaceman-dmm.sh dmdoc
      - name: Generate documentation
        run: |
          ~/dmdoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@dc18a3c6b46d56484cb63f291becd7ed4f0269b9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dmdoc
          target-folder: docs/dmdoc
          clean: true
